import {
    Users,
    GraduationCap,
    LayoutGrid,
    BookOpen,
    ClipboardCheck,
    CreditCard,
    MessageSquare,
    FileText,
    BarChart3,
    Settings,
    School,
    PenTool,
    PartyPopper,
    Library,
    Building2,
    CalendarDays,
    Bus,
    UserCheck,
    History,
} from "lucide-react";
import { RouteItem, SidebarConfig, HeaderConfig } from "./types";

export const adminRoutes: RouteItem[] = [
    {
        label: "Dashboard",
        icon: LayoutGrid,
        href: "/admin",
    },
    {
        label: "Users",
        icon: Users,
        submenu: [
            { label: "Overview", href: "/admin/users" },
            { label: "Administrators", href: "/admin/users/administrators" },
            { label: "Teachers", href: "/admin/users/teachers" },
            { label: "Students", href: "/admin/users/students" },
            { label: "Parents", href: "/admin/users/parents" },
        ],
    },
    {
        label: "Academic",
        icon: GraduationCap,
        submenu: [
            { label: "Overview", href: "/admin/academic" },
            { label: "Academic Years", href: "/admin/academic/academic-years" },
            { label: "Terms", href: "/admin/academic/terms" },
            { label: "Departments", href: "/admin/academic/departments" },
            { label: "Grades", href: "/admin/academic/grades" },
            { label: "Curriculum", href: "/admin/academic/curriculum" },
            { label: "Syllabus", href: "/admin/academic/syllabus" },
            { label: "Promotion", href: "/admin/academic/promotion" },
        ],
    },
    {
        label: "Classes",
        icon: School,
        submenu: [
            { label: "Class List", href: "/admin/classes" },
            { label: "Sections", href: "/admin/classes/sections" },
            { label: "Rooms", href: "/admin/classes/rooms" },
        ],
    },
    {
        label: "Teaching",
        icon: PenTool,
        submenu: [
            { label: "Overview", href: "/admin/teaching" },
            { label: "Subjects", href: "/admin/teaching/subjects" },
            { label: "Lessons", href: "/admin/teaching/lessons" },
            { label: "Timetable", href: "/admin/teaching/timetable" },
        ],
    },
    {
        label: "Assessment",
        icon: BookOpen,
        submenu: [
            { label: "Overview", href: "/admin/assessment" },
            { label: "Exam Types", href: "/admin/assessment/exam-types" },
            { label: "Exams", href: "/admin/assessment/exams" },
            { label: "Marks Entry", href: "/admin/assessment/marks-entry" },
            { label: "Marks Audit", href: "/admin/assessment/marks-audit" },
            { label: "Mark Sheet", href: "/admin/assessment/consolidated-mark-sheet" },
            { label: "Subject Performance", href: "/admin/assessment/subject-performance" },
            { label: "Co-Scholastic", href: "/admin/assessment/co-scholastic" },
            { label: "Assignments", href: "/admin/assessment/assignments" },
            { label: "Results", href: "/admin/assessment/results" },
            { label: "Report Cards", href: "/admin/assessment/report-cards" },
        ],
    },
    {
        label: "Attendance",
        icon: ClipboardCheck,
        submenu: [
            { label: "Overview", href: "/admin/attendance" },
            { label: "Student Attendance", href: "/admin/attendance/students" },
            { label: "Teacher Attendance", href: "/admin/attendance/teachers" },
            { label: "Reports", href: "/admin/attendance/reports" },
        ],
    },
    {
        label: "Finance",
        icon: CreditCard,
        submenu: [
            { label: "Overview", href: "/admin/finance" },
            { label: "Fee Structure", href: "/admin/finance/fee-structure" },
            { label: "Payments", href: "/admin/finance/payments" },
            { label: "Receipt Verification", href: "/admin/finance/receipt-verification" },
            { label: "Analytics", href: "/admin/finance/analytics" },
            { label: "Scholarships", href: "/admin/finance/scholarships" },
            { label: "Payroll", href: "/admin/finance/payroll" },
            { label: "Expenses", href: "/admin/finance/expenses" },
            { label: "Budget", href: "/admin/finance/budget" },
        ],
    },
    {
        label: "Communication",
        icon: MessageSquare,
        submenu: [
            { label: "Overview", href: "/admin/communication" },
            { label: "Messages", href: "/admin/communication/messages" },
            { label: "Announcements", href: "/admin/communication/announcements" },
            { label: "Bulk Messaging", href: "/admin/communication/bulk-messaging" },
            { label: "Templates", href: "/admin/communication/templates" },
            { label: "Notifications", href: "/admin/communication/notifications" },
            { label: "Parent Meetings", href: "/admin/communication/parent-meetings" },
            { label: "WhatsApp Profile", href: "/admin/communication/whatsapp-profile" },
        ],
    },
    {
        label: "Library",
        icon: Library,
        submenu: [
            { label: "Overview", href: "/admin/library" },
            { label: "Books", href: "/admin/library/books" },
            { label: "Reports", href: "/admin/library/reports" },
        ],
    },
    {
        label: "Transport",
        icon: Bus,
        submenu: [
            { label: "Overview", href: "/admin/transport" },
            { label: "Vehicles", href: "/admin/transport/vehicles" },
            { label: "Routes", href: "/admin/transport/routes" },
            { label: "Attendance", href: "/admin/transport/attendance" },
        ],
    },
    {
        label: "Hostel",
        icon: Building2,
        submenu: [
            { label: "Overview", href: "/admin/hostel" },
            { label: "Rooms", href: "/admin/hostel/rooms" },
            { label: "Visitors", href: "/admin/hostel/visitors" },
            { label: "Fees", href: "/admin/hostel/fees" },
            { label: "Complaints", href: "/admin/hostel/complaints" },
        ],
    },
    {
        label: "Admissions",
        icon: GraduationCap,
        href: "/admin/admissions",
    },
    {
        label: "Alumni",
        icon: UserCheck,
        submenu: [
            { label: "Directory", href: "/admin/alumni" },
            { label: "Communication", href: "/admin/alumni/communication" },
            { label: "Statistics", href: "/admin/alumni/statistics" },
        ],
    },
    {
        label: "Calendar",
        icon: CalendarDays,
        href: "/admin/calendar",
    },
    {
        label: "Events",
        icon: PartyPopper,
        href: "/admin/events",
    },
    {
        label: "Documents",
        icon: FileText,
        submenu: [
            { label: "Overview", href: "/admin/documents" },
            { label: "ID Cards", href: "/admin/id-cards" },
            { label: "Certificates", href: "/admin/certificates" },
        ],
    },
    {
        label: "Reports",
        icon: BarChart3,
        submenu: [
            { label: "Overview", href: "/admin/reports" },
            { label: "Academic Reports", href: "/admin/reports/academic" },
            { label: "Financial Reports", href: "/admin/reports/financial" },
            { label: "Attendance Reports", href: "/admin/reports/attendance" },
            { label: "Performance Analytics", href: "/admin/reports/performance" },
            { label: "Report Builder", href: "/admin/reports/builder" },
            { label: "Scheduled Reports", href: "/admin/reports/scheduled" },
            { label: "Comparative", href: "/admin/reports/comparative" },
        ],
    },
    {
        label: "Audit Logs",
        icon: History,
        href: "/admin/audit-logs",
    },
    {
        label: "Settings",
        icon: Settings,
        submenu: [
            { label: "General", href: "/admin/settings" },
            { label: "Branding", href: "/admin/settings/branding" },
            { label: "Permissions", href: "/admin/settings/permissions" },
            { label: "Notifications", href: "/admin/settings/notifications" },
            { label: "Two-Factor Auth", href: "/admin/settings/two-factor" },
            { label: "Payment Config", href: "/admin/settings/payment-configuration" },
            { label: "Sessions", href: "/admin/settings/sessions" },
            { label: "Backups", href: "/admin/settings/backups" },
        ],
    },
];

export const adminSidebarConfig: SidebarConfig = {
    routes: adminRoutes,
    portalLabel: "Admin Portal",
    dashboardHref: "/admin",
    accountLabel: "Admin Account",
};

export const adminHeaderConfig: HeaderConfig = {
    dashboardHref: "/admin",
    pageTitleMappings: {
        "/admin/users": "Users",
        "/admin/academic": "Academic",
        "/admin/classes": "Classes",
        "/admin/teaching": "Teaching",
        "/admin/assessment": "Assessment",
        "/admin/attendance": "Attendance",
        "/admin/finance": "Finance",
        "/admin/communication": "Communication",
        "/admin/library": "Library",
        "/admin/transport": "Transport",
        "/admin/hostel": "Hostel",
        "/admin/admissions": "Admissions",
        "/admin/alumni": "Alumni",
        "/admin/calendar": "Calendar",
        "/admin/events": "Events",
        "/admin/documents": "Documents",
        "/admin/id-cards": "ID Cards",
        "/admin/certificates": "Certificates",
        "/admin/reports": "Reports",
        "/admin/audit-logs": "Audit Logs",
        "/admin/settings": "Settings",
        "/admin": "Dashboard",
    },
};
