-- CreateTable: Unified SchoolSettings model
CREATE TABLE "school_settings" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "onboardingCompleted" BOOLEAN NOT NULL DEFAULT false,
    "onboardingStep" INTEGER NOT NULL DEFAULT 0,
    "schoolName" TEXT NOT NULL DEFAULT 'School Name',
    "schoolAddress" TEXT,
    "schoolPhone" TEXT,
    "schoolEmail" TEXT,
    "schoolLogo" TEXT,
    "schoolWebsite" TEXT,
    "schoolFax" TEXT,
    "affiliationNumber" TEXT,
    "schoolCode" TEXT,
    "board" TEXT DEFAULT 'CBSE',
    "timezone" TEXT NOT NULL DEFAULT 'UTC',
    "tagline" TEXT,
    "currentAcademicYear" TEXT NOT NULL DEFAULT '',
    "currentTerm" TEXT NOT NULL DEFAULT '',
    "defaultGradingScale" TEXT NOT NULL DEFAULT 'PERCENTAGE',
    "attendanceThreshold" INTEGER NOT NULL DEFAULT 75,
    "lateArrivalMinutes" INTEGER NOT NULL DEFAULT 15,
    "passingGrade" INTEGER NOT NULL DEFAULT 50,
    "autoAttendance" BOOLEAN NOT NULL DEFAULT false,
    "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false,
    "twoFactorRequired" BOOLEAN NOT NULL DEFAULT false,
    "twoFactorMethods" TEXT[] DEFAULT ARRAY['SMS', 'EMAIL']::TEXT[],
    "sessionTimeout" INTEGER NOT NULL DEFAULT 480,
    "maxConcurrentSessions" INTEGER NOT NULL DEFAULT 3,
    "forceLogoutOnPasswordChange" BOOLEAN NOT NULL DEFAULT true,
    "passwordMinLength" INTEGER NOT NULL DEFAULT 8,
    "passwordRequireUppercase" BOOLEAN NOT NULL DEFAULT true,
    "passwordRequireLowercase" BOOLEAN NOT NULL DEFAULT true,
    "passwordRequireNumbers" BOOLEAN NOT NULL DEFAULT true,
    "passwordRequireSpecialChars" BOOLEAN NOT NULL DEFAULT false,
    "passwordExpiry" INTEGER NOT NULL DEFAULT 90,
    "ipWhitelistEnabled" BOOLEAN NOT NULL DEFAULT false,
    "allowedIPs" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "blockUnknownIPs" BOOLEAN NOT NULL DEFAULT false,
    "auditLoggingEnabled" BOOLEAN NOT NULL DEFAULT true,
    "auditLogLevel" TEXT NOT NULL DEFAULT 'INFO',
    "auditLogRetention" INTEGER NOT NULL DEFAULT 365,
    "encryptSensitiveData" BOOLEAN NOT NULL DEFAULT true,
    "encryptionLevel" TEXT NOT NULL DEFAULT 'AES-256',
    "rateLimitEnabled" BOOLEAN NOT NULL DEFAULT true,
    "maxRequestsPerMinute" INTEGER NOT NULL DEFAULT 100,
    "requireApiKey" BOOLEAN NOT NULL DEFAULT false,
    "autoBackupEnabled" BOOLEAN NOT NULL DEFAULT true,
    "backupFrequency" TEXT NOT NULL DEFAULT 'DAILY',
    "backupRetention" INTEGER NOT NULL DEFAULT 30,
    "includeFiles" BOOLEAN NOT NULL DEFAULT true,
    "encryptBackups" BOOLEAN NOT NULL DEFAULT true,
    "allowDataExport" BOOLEAN NOT NULL DEFAULT true,
    "exportFormats" TEXT[] DEFAULT ARRAY['CSV', 'JSON', 'PDF']::TEXT[],
    "requireApproval" BOOLEAN NOT NULL DEFAULT true,
    "studentDataRetention" INTEGER NOT NULL DEFAULT 7,
    "messageRetention" INTEGER NOT NULL DEFAULT 90,
    "autoCleanup" BOOLEAN NOT NULL DEFAULT false,
    "storageQuota" INTEGER NOT NULL DEFAULT 1,
    "compressionEnabled" BOOLEAN NOT NULL DEFAULT true,
    "autoArchive" BOOLEAN NOT NULL DEFAULT true,
    "archiveAfterDays" INTEGER NOT NULL DEFAULT 365,
    "emailEnabled" BOOLEAN NOT NULL DEFAULT true,
    "emailAdmissionUpdates" BOOLEAN NOT NULL DEFAULT true,
    "emailFeeReminders" BOOLEAN NOT NULL DEFAULT true,
    "emailExamNotifications" BOOLEAN NOT NULL DEFAULT true,
    "emailAttendanceAlerts" BOOLEAN NOT NULL DEFAULT true,
    "emailSystemUpdates" BOOLEAN NOT NULL DEFAULT true,
    "smsEnabled" BOOLEAN NOT NULL DEFAULT false,
    "smsAdmissionUpdates" BOOLEAN NOT NULL DEFAULT false,
    "smsFeeReminders" BOOLEAN NOT NULL DEFAULT true,
    "smsExamNotifications" BOOLEAN NOT NULL DEFAULT true,
    "smsAttendanceAlerts" BOOLEAN NOT NULL DEFAULT true,
    "smsEmergencyAlerts" BOOLEAN NOT NULL DEFAULT true,
    "whatsappEnabled" BOOLEAN NOT NULL DEFAULT false,
    "whatsappAdmissionUpdates" BOOLEAN NOT NULL DEFAULT false,
    "whatsappFeeReminders" BOOLEAN NOT NULL DEFAULT true,
    "whatsappExamNotifications" BOOLEAN NOT NULL DEFAULT true,
    "whatsappAttendanceAlerts" BOOLEAN NOT NULL DEFAULT false,
    "whatsappGeneralUpdates" BOOLEAN NOT NULL DEFAULT false,
    "pushEnabled" BOOLEAN NOT NULL DEFAULT true,
    "pushAdmissionUpdates" BOOLEAN NOT NULL DEFAULT true,
    "pushFeeReminders" BOOLEAN NOT NULL DEFAULT true,
    "pushExamNotifications" BOOLEAN NOT NULL DEFAULT true,
    "pushAttendanceAlerts" BOOLEAN NOT NULL DEFAULT true,
    "pushSystemMaintenance" BOOLEAN NOT NULL DEFAULT true,
    "notifyEnrollment" BOOLEAN NOT NULL DEFAULT true,
    "notifyPayment" BOOLEAN NOT NULL DEFAULT true,
    "notifyAttendance" BOOLEAN NOT NULL DEFAULT true,
    "notifyExamResults" BOOLEAN NOT NULL DEFAULT true,
    "notifyLeaveApps" BOOLEAN NOT NULL DEFAULT true,
    "enrollmentNotificationChannels" TEXT[] DEFAULT ARRAY['EMAIL', 'IN_APP']::TEXT[],
    "paymentNotificationChannels" TEXT[] DEFAULT ARRAY['EMAIL', 'IN_APP']::TEXT[],
    "attendanceNotificationChannels" TEXT[] DEFAULT ARRAY['SMS', 'IN_APP']::TEXT[],
    "examResultNotificationChannels" TEXT[] DEFAULT ARRAY['EMAIL', 'IN_APP']::TEXT[],
    "leaveAppNotificationChannels" TEXT[] DEFAULT ARRAY['EMAIL', 'IN_APP']::TEXT[],
    "quietHoursEnabled" BOOLEAN NOT NULL DEFAULT true,
    "quietHoursStart" TEXT NOT NULL DEFAULT '22:00',
    "quietHoursEnd" TEXT NOT NULL DEFAULT '08:00',
    "weekendNotifications" BOOLEAN NOT NULL DEFAULT false,
    "batchNotifications" BOOLEAN NOT NULL DEFAULT true,
    "immediateEmergency" BOOLEAN NOT NULL DEFAULT true,
    "digestFrequency" TEXT NOT NULL DEFAULT 'DAILY',
    "defaultTheme" TEXT NOT NULL DEFAULT 'LIGHT',
    "defaultColorTheme" TEXT NOT NULL DEFAULT 'blue',
    "primaryColor" TEXT NOT NULL DEFAULT '#3b82f6',
    "secondaryColor" TEXT NOT NULL DEFAULT '#8b5cf6',
    "accentColor" TEXT,
    "logoUrl" TEXT,
    "faviconUrl" TEXT,
    "emailLogo" TEXT,
    "emailFooter" TEXT,
    "emailSignature" TEXT,
    "letterheadLogo" TEXT,
    "letterheadText" TEXT,
    "documentFooter" TEXT,
    "facebookUrl" TEXT,
    "twitterUrl" TEXT,
    "linkedinUrl" TEXT,
    "instagramUrl" TEXT,
    "language" TEXT NOT NULL DEFAULT 'en',
    "dateFormat" TEXT NOT NULL DEFAULT 'mdy',
    "enableOnlinePayment" BOOLEAN NOT NULL DEFAULT false,
    "enableOfflineVerification" BOOLEAN NOT NULL DEFAULT true,
    "onlinePaymentGateway" TEXT,
    "maxReceiptSizeMB" INTEGER NOT NULL DEFAULT 5,
    "allowedReceiptFormats" TEXT NOT NULL DEFAULT 'jpg,jpeg,png,pdf',
    "autoNotifyOnVerification" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "school_settings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "school_settings_schoolId_key" ON "school_settings"("schoolId");

-- CreateIndex
CREATE INDEX "school_settings_schoolId_idx" ON "school_settings"("schoolId");

-- AddForeignKey
ALTER TABLE "school_settings" ADD CONSTRAINT "school_settings_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Note: Old tables are NOT dropped in this migration for safety
-- After verifying the migration with the TypeScript script, you can manually drop:
-- DROP TABLE IF EXISTS "SchoolSecuritySettings";
-- DROP TABLE IF EXISTS "SchoolDataManagementSettings";
-- DROP TABLE IF EXISTS "SchoolNotificationSettings";
-- DROP TABLE IF EXISTS "system_settings";
