// Standard fee types for Indian schools
export const STANDARD_FEE_TYPES = [
  {
    name: "Tuition Fee",
    description: "Regular tuition charges for academic instruction",
    amount: 10000,
    frequency: "ANNUAL" as const,
    isOptional: false,
  },
  {
    name: "Admission Fee",
    description: "One-time admission charges for new students",
    amount: 5000,
    frequency: "ONE_TIME" as const,
    isOptional: false,
  },
  {
    name: "Development Fee",
    description: "Infrastructure and facility development charges",
    amount: 3000,
    frequency: "ANNUAL" as const,
    isOptional: false,
  },
  {
    name: "Examination Fee",
    description: "Charges for conducting examinations and assessments",
    amount: 1500,
    frequency: "ANNUAL" as const,
    isOptional: false,
  },
  {
    name: "Library Fee",
    description: "Library access and book maintenance charges",
    amount: 1000,
    frequency: "ANNUAL" as const,
    isOptional: false,
  },
  {
    name: "Laboratory Fee",
    description: "Science and computer lab usage charges",
    amount: 2000,
    frequency: "ANNUAL" as const,
    isOptional: false,
  },
  {
    name: "Sports Fee",
    description: "Sports facilities and equipment charges",
    amount: 1500,
    frequency: "ANNUAL" as const,
    isOptional: true,
  },
  {
    name: "Transport Fee",
    description: "School bus and transportation charges",
    amount: 12000,
    frequency: "ANNUAL" as const,
    isOptional: true,
  },
  {
    name: "Hostel Fee",
    description: "Boarding and lodging charges for hostel students",
    amount: 50000,
    frequency: "ANNUAL" as const,
    isOptional: true,
  },
  {
    name: "Computer Fee",
    description: "Computer lab and IT infrastructure charges",
    amount: 2000,
    frequency: "ANNUAL" as const,
    isOptional: false,
  },
  {
    name: "Activity Fee",
    description: "Co-curricular and extracurricular activity charges",
    amount: 1000,
    frequency: "ANNUAL" as const,
    isOptional: true,
  },
  {
    name: "Uniform Fee",
    description: "School uniform and dress code charges",
    amount: 3000,
    frequency: "ANNUAL" as const,
    isOptional: true,
  },
  {
    name: "Stationery Fee",
    description: "Books, notebooks, and stationery charges",
    amount: 2000,
    frequency: "ANNUAL" as const,
    isOptional: true,
  },
  {
    name: "Medical Fee",
    description: "Health checkup and medical facility charges",
    amount: 500,
    frequency: "ANNUAL" as const,
    isOptional: true,
  },
  {
    name: "Security Deposit",
    description: "Refundable security deposit",
    amount: 5000,
    frequency: "ONE_TIME" as const,
    isOptional: false,
  },
];
