/**
 * Permission names enum for type safety
 * Shared between server and client
 */
export const PERMISSIONS = {
    // User Management
    CREATE_USER: 'CREATE_USER',
    READ_USER: 'READ_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    EXPORT_USER: 'EXPORT_USER',
    IMPORT_USER: 'IMPORT_USER',

    // Student Management
    CREATE_STUDENT: 'CREATE_STUDENT',
    READ_STUDENT: 'READ_STUDENT',
    UPDATE_STUDENT: 'UPDATE_STUDENT',
    DELETE_STUDENT: 'DELETE_STUDENT',
    EXPORT_STUDENT: 'EXPORT_STUDENT',
    IMPORT_STUDENT: 'IMPORT_STUDENT',

    // Teacher Management
    CREATE_TEACHER: 'CREATE_TEACHER',
    READ_TEACHER: 'READ_TEACHER',
    UPDATE_TEACHER: 'UPDATE_TEACHER',
    DELETE_TEACHER: 'DELETE_TEACHER',
    EXPORT_TEACHER: 'EXPORT_TEACHER',

    // Parent Management
    CREATE_PARENT: 'CREATE_PARENT',
    READ_PARENT: 'READ_PARENT',
    UPDATE_PARENT: 'UPDATE_PARENT',
    DELETE_PARENT: 'DELETE_PARENT',

    // Class Management
    CREATE_CLASS: 'CREATE_CLASS',
    READ_CLASS: 'READ_CLASS',
    UPDATE_CLASS: 'UPDATE_CLASS',
    DELETE_CLASS: 'DELETE_CLASS',

    // Subject Management
    CREATE_SUBJECT: 'CREATE_SUBJECT',
    READ_SUBJECT: 'READ_SUBJECT',
    UPDATE_SUBJECT: 'UPDATE_SUBJECT',
    DELETE_SUBJECT: 'DELETE_SUBJECT',

    // Exam Management
    CREATE_EXAM: 'CREATE_EXAM',
    READ_EXAM: 'READ_EXAM',
    UPDATE_EXAM: 'UPDATE_EXAM',
    DELETE_EXAM: 'DELETE_EXAM',
    PUBLISH_EXAM: 'PUBLISH_EXAM',

    // Assignment Management
    CREATE_ASSIGNMENT: 'CREATE_ASSIGNMENT',
    READ_ASSIGNMENT: 'READ_ASSIGNMENT',
    UPDATE_ASSIGNMENT: 'UPDATE_ASSIGNMENT',
    DELETE_ASSIGNMENT: 'DELETE_ASSIGNMENT',

    // Attendance Management
    CREATE_ATTENDANCE: 'CREATE_ATTENDANCE',
    READ_ATTENDANCE: 'READ_ATTENDANCE',
    UPDATE_ATTENDANCE: 'UPDATE_ATTENDANCE',
    EXPORT_ATTENDANCE: 'EXPORT_ATTENDANCE',

    // Fee Management
    CREATE_FEE: 'CREATE_FEE',
    READ_FEE: 'READ_FEE',
    UPDATE_FEE: 'UPDATE_FEE',
    DELETE_FEE: 'DELETE_FEE',

    // Payment Management
    CREATE_PAYMENT: 'CREATE_PAYMENT',
    READ_PAYMENT: 'READ_PAYMENT',
    UPDATE_PAYMENT: 'UPDATE_PAYMENT',
    DELETE_PAYMENT: 'DELETE_PAYMENT',
    APPROVE_PAYMENT: 'APPROVE_PAYMENT',
    EXPORT_PAYMENT: 'EXPORT_PAYMENT',

    // Communication
    CREATE_ANNOUNCEMENT: 'CREATE_ANNOUNCEMENT',
    READ_ANNOUNCEMENT: 'READ_ANNOUNCEMENT',
    UPDATE_ANNOUNCEMENT: 'UPDATE_ANNOUNCEMENT',
    DELETE_ANNOUNCEMENT: 'DELETE_ANNOUNCEMENT',
    PUBLISH_ANNOUNCEMENT: 'PUBLISH_ANNOUNCEMENT',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    READ_MESSAGE: 'READ_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',

    // Document Management
    CREATE_DOCUMENT: 'CREATE_DOCUMENT',
    READ_DOCUMENT: 'READ_DOCUMENT',
    UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
    DELETE_DOCUMENT: 'DELETE_DOCUMENT',

    // Reports
    CREATE_REPORT: 'CREATE_REPORT',
    READ_REPORT: 'READ_REPORT',
    EXPORT_REPORT: 'EXPORT_REPORT',

    // Library Management
    CREATE_BOOK: 'CREATE_BOOK',
    READ_BOOK: 'READ_BOOK',
    UPDATE_BOOK: 'UPDATE_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',

    // Transport Management
    CREATE_VEHICLE: 'CREATE_VEHICLE',
    READ_VEHICLE: 'READ_VEHICLE',
    UPDATE_VEHICLE: 'UPDATE_VEHICLE',
    DELETE_VEHICLE: 'DELETE_VEHICLE',
    CREATE_ROUTE: 'CREATE_ROUTE',
    READ_ROUTE: 'READ_ROUTE',
    UPDATE_ROUTE: 'UPDATE_ROUTE',
    DELETE_ROUTE: 'DELETE_ROUTE',

    // Admission Management
    CREATE_APPLICATION: 'CREATE_APPLICATION',
    READ_APPLICATION: 'READ_APPLICATION',
    UPDATE_APPLICATION: 'UPDATE_APPLICATION',
    DELETE_APPLICATION: 'DELETE_APPLICATION',
    APPROVE_APPLICATION: 'APPROVE_APPLICATION',
    REJECT_APPLICATION: 'REJECT_APPLICATION',

    // Certificate Management
    CREATE_CERTIFICATE: 'CREATE_CERTIFICATE',
    READ_CERTIFICATE: 'READ_CERTIFICATE',
    UPDATE_CERTIFICATE: 'UPDATE_CERTIFICATE',
    DELETE_CERTIFICATE: 'DELETE_CERTIFICATE',

    // Backup Management
    CREATE_BACKUP: 'CREATE_BACKUP',
    READ_BACKUP: 'READ_BACKUP',
    DELETE_BACKUP: 'DELETE_BACKUP',

    // System Settings
    READ_SETTINGS: 'READ_SETTINGS',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',

    // Student Promotion Management
    CREATE_PROMOTION: 'CREATE_PROMOTION',
    READ_PROMOTION: 'READ_PROMOTION',
    DELETE_PROMOTION: 'DELETE_PROMOTION',

    // Graduation Ceremony Management
    CREATE_GRADUATION: 'CREATE_GRADUATION',
    READ_GRADUATION: 'READ_GRADUATION',

    // Alumni Management (Admin)
    CREATE_ALUMNI: 'CREATE_ALUMNI',
    READ_ALUMNI: 'READ_ALUMNI',
    UPDATE_ALUMNI: 'UPDATE_ALUMNI',
    DELETE_ALUMNI: 'DELETE_ALUMNI',
    EXPORT_ALUMNI: 'EXPORT_ALUMNI',

    // Alumni Portal (for graduated students)
    READ_ALUMNI_PORTAL: 'READ_ALUMNI_PORTAL',
    UPDATE_ALUMNI_PORTAL: 'UPDATE_ALUMNI_PORTAL',
    // Marks Management
    CREATE_MARKS: 'CREATE_MARKS',
    READ_MARKS: 'READ_MARKS',
    UPDATE_MARKS: 'UPDATE_MARKS',
    DELETE_MARKS: 'DELETE_MARKS',
    EXPORT_MARKS: 'EXPORT_MARKS',
    IMPORT_MARKS: 'IMPORT_MARKS',

    // Result Management
    CREATE_RESULT: 'CREATE_RESULT',
    READ_RESULT: 'READ_RESULT',
    PUBLISH_RESULT: 'PUBLISH_RESULT',

    // Scholarship Management
    CREATE_SCHOLARSHIP: 'CREATE_SCHOLARSHIP',
    READ_SCHOLARSHIP: 'READ_SCHOLARSHIP',
    UPDATE_SCHOLARSHIP: 'UPDATE_SCHOLARSHIP',
    DELETE_SCHOLARSHIP: 'DELETE_SCHOLARSHIP',
    APPROVE_SCHOLARSHIP: 'APPROVE_SCHOLARSHIP',

    // Payroll Management
    CREATE_PAYROLL: 'CREATE_PAYROLL',
    READ_PAYROLL: 'READ_PAYROLL',
    UPDATE_PAYROLL: 'UPDATE_PAYROLL',
    DELETE_PAYROLL: 'DELETE_PAYROLL',
    APPROVE_PAYROLL: 'APPROVE_PAYROLL',

    // Budget Management
    CREATE_BUDGET: 'CREATE_BUDGET',
    READ_BUDGET: 'READ_BUDGET',
    UPDATE_BUDGET: 'UPDATE_BUDGET',
    DELETE_BUDGET: 'DELETE_BUDGET',

    // Expense Management
    CREATE_EXPENSE: 'CREATE_EXPENSE',
    READ_EXPENSE: 'READ_EXPENSE',
    UPDATE_EXPENSE: 'UPDATE_EXPENSE',
    DELETE_EXPENSE: 'DELETE_EXPENSE',
    APPROVE_EXPENSE: 'APPROVE_EXPENSE',

    // Timetable Management
    CREATE_TIMETABLE: 'CREATE_TIMETABLE',
    READ_TIMETABLE: 'READ_TIMETABLE',
    UPDATE_TIMETABLE: 'UPDATE_TIMETABLE',
    DELETE_TIMETABLE: 'DELETE_TIMETABLE',

    // Syllabus Management
    CREATE_SYLLABUS: 'CREATE_SYLLABUS',
    READ_SYLLABUS: 'READ_SYLLABUS',
    UPDATE_SYLLABUS: 'UPDATE_SYLLABUS',
    DELETE_SYLLABUS: 'DELETE_SYLLABUS',

    // Calendar/Event Management
    CREATE_CALENDAR: 'CREATE_CALENDAR',
    READ_CALENDAR: 'READ_CALENDAR',
    UPDATE_CALENDAR: 'UPDATE_CALENDAR',
    DELETE_CALENDAR: 'DELETE_CALENDAR',

    // Event Management
    CREATE_EVENT: 'CREATE_EVENT',
    READ_EVENT: 'READ_EVENT',
    UPDATE_EVENT: 'UPDATE_EVENT',
    DELETE_EVENT: 'DELETE_EVENT',
} as const;

export type Permission = keyof typeof PERMISSIONS;
