"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import {
  ChevronLeft, Edit, Trash2, PlusCircle,
  Building2, BookOpen, GraduationCap,
  Loader2, AlertCircle, X, UserPlus, Sparkles
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Checkbox } from "@/components/ui/checkbox";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import toast from "react-hot-toast";

// Import schema validation and server actions
import { departmentSchema, DepartmentFormValues, departmentUpdateSchema, DepartmentUpdateFormValues } from "@/lib/schemaValidation/departmentsSchemaValidation";
import {
  getDepartments,
  getDepartmentById,
  createDepartment,
  updateDepartment,
  deleteDepartment,
  getAvailableTeachersForDepartment,
  getAvailableSubjectsForDepartment,
  assignTeacherToDepartment,
  assignSubjectToDepartment,
  removeTeacherFromDepartment,
  removeSubjectFromDepartment,
  autoGenerateDepartments,
  getAvailableDepartmentTemplates,
} from "@/lib/actions/departmentsAction";
import { STANDARD_DEPARTMENTS } from "@/lib/constants/academic-standards";

interface DepartmentDetail {
  id: string;
  name: string;
  description?: string | null;
  subjects: Array<{ id: string; name: string; code: string }>;
  teachers: Array<{
    id: string;
    employeeId: string;
    user: { firstName: string; lastName: string; email: string; avatar: string | null };
  }>;
}

export default function DepartmentsPage() {
  const [departments, setDepartments] = useState<any[]>([]);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [manageDialogOpen, setManageDialogOpen] = useState(false);
  const [selectedDepartmentId, setSelectedDepartmentId] = useState<string | null>(null);
  const [selectedDepartment, setSelectedDepartment] = useState<DepartmentDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [autoGenerating, setAutoGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // For adding teachers/subjects
  const [availableTeachers, setAvailableTeachers] = useState<any[]>([]);
  const [availableSubjects, setAvailableSubjects] = useState<any[]>([]);
  const [loadingAvailable, setLoadingAvailable] = useState(false);
  const [selectedTeacherId, setSelectedTeacherId] = useState("");
  const [selectedSubjectId, setSelectedSubjectId] = useState("");

  // For auto-generate checklist
  const [autoGenerateDialogOpen, setAutoGenerateDialogOpen] = useState(false);
  const [availableTemplates, setAvailableTemplates] = useState<typeof STANDARD_DEPARTMENTS>([]);
  const [selectedTemplates, setSelectedTemplates] = useState<string[]>([]);

  const form = useForm<DepartmentFormValues>({
    resolver: zodResolver(departmentSchema),
    defaultValues: {
      name: "",
      description: "",
    },
  });

  useEffect(() => {
    fetchDepartments();
  }, []);

  async function fetchDepartments() {
    setLoading(true);
    setError(null);

    try {
      const result = await getDepartments();

      if (result.success) {
        setDepartments(result.data || []);
      } else {
        setError(result.error || "An error occurred");
        toast.error(result.error || "An error occurred");
      }
    } catch (err) {
      setError("An unexpected error occurred");
      toast.error("An unexpected error occurred");
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  async function onSubmit(values: DepartmentFormValues) {
    try {
      let result;

      if (selectedDepartmentId) {
        // Update existing department
        const updateData: DepartmentUpdateFormValues = { ...values, id: selectedDepartmentId };
        result = await updateDepartment(updateData);
      } else {
        // Create new department
        result = await createDepartment(values);
      }

      if (result.success) {
        toast.success(`Department ${selectedDepartmentId ? "updated" : "created"} successfully`);
        setDialogOpen(false);
        form.reset();
        setSelectedDepartmentId(null);
        fetchDepartments();
      } else {
        toast.error(result.error || "An error occurred");
      }
    } catch (err) {
      console.error(err);
      toast.error("An unexpected error occurred");
    }
  }

  function handleEdit(id: string) {
    const departmentToEdit = departments.find(dept => dept.id === id);
    if (departmentToEdit) {
      form.reset({
        name: departmentToEdit.name,
        description: departmentToEdit.description,
      });
      setSelectedDepartmentId(id);
      setDialogOpen(true);
    }
  }

  function handleDelete(id: string) {
    setSelectedDepartmentId(id);
    setDeleteDialogOpen(true);
  }

  async function confirmDelete() {
    if (selectedDepartmentId) {
      try {
        const result = await deleteDepartment(selectedDepartmentId);

        if (result.success) {
          toast.success("Department deleted successfully");
          setDeleteDialogOpen(false);
          setSelectedDepartmentId(null);
          fetchDepartments();
        } else {
          toast.error(result.error || "Failed to delete department");
        }
      } catch (err) {
        console.error(err);
        toast.error("An unexpected error occurred");
      }
    }
  }

  function handleAddNew() {
    form.reset({ name: "", description: "" });
    setSelectedDepartmentId(null);
    setDialogOpen(true);
  }

  async function handleAutoGenerate() {
    // Load available templates and open dialog
    const result = await getAvailableDepartmentTemplates();
    if (result.success && result.data) {
      setAvailableTemplates(result.data);
      setSelectedTemplates(result.data.map(d => d.name)); // Select all by default
      setAutoGenerateDialogOpen(true);
    } else {
      toast.error(result.error || "All departments already exist");
    }
  }

  async function confirmAutoGenerate() {
    if (selectedTemplates.length === 0) {
      toast.error("Please select at least one department");
      return;
    }

    setAutoGenerating(true);
    try {
      const result = await autoGenerateDepartments(selectedTemplates);
      if (result.success) {
        toast.success(`Auto-generated ${result.count} departments successfully`);
        setAutoGenerateDialogOpen(false);
        fetchDepartments();
      } else {
        toast.error(result.error || "Failed to auto-generate departments");
      }
    } catch (err) {
      console.error(err);
      toast.error("An unexpected error occurred");
    } finally {
      setAutoGenerating(false);
    }
  }

  function toggleTemplate(name: string) {
    setSelectedTemplates(prev =>
      prev.includes(name)
        ? prev.filter(n => n !== name)
        : [...prev, name]
    );
  }

  function selectAllTemplates() {
    setSelectedTemplates(availableTemplates.map(d => d.name));
  }

  function clearAllTemplates() {
    setSelectedTemplates([]);
  }

  async function handleManage(id: string) {
    setSelectedDepartmentId(id);
    setLoadingAvailable(true);
    setManageDialogOpen(true);

    try {
      const [deptResult, teachersResult, subjectsResult] = await Promise.all([
        getDepartmentById(id),
        getAvailableTeachersForDepartment(id),
        getAvailableSubjectsForDepartment(id),
      ]);

      if (deptResult.success && deptResult.data) {
        setSelectedDepartment(deptResult.data as DepartmentDetail);
      }
      if (teachersResult.success && teachersResult.data) {
        setAvailableTeachers(teachersResult.data);
      }
      if (subjectsResult.success && subjectsResult.data) {
        setAvailableSubjects(subjectsResult.data);
      }
    } catch (err) {
      console.error(err);
      toast.error("Failed to load department details");
    } finally {
      setLoadingAvailable(false);
    }
  }

  async function handleAddTeacher() {
    if (!selectedTeacherId || !selectedDepartmentId) return;

    const result = await assignTeacherToDepartment(selectedTeacherId, selectedDepartmentId);
    if (result.success) {
      toast.success("Teacher added to department");
      setSelectedTeacherId("");
      handleManage(selectedDepartmentId); // Refresh
      fetchDepartments();
    } else {
      toast.error(result.error || "Failed to add teacher");
    }
  }

  async function handleRemoveTeacher(teacherId: string) {
    if (!selectedDepartmentId) return;

    const result = await removeTeacherFromDepartment(teacherId, selectedDepartmentId);
    if (result.success) {
      toast.success("Teacher removed from department");
      handleManage(selectedDepartmentId); // Refresh
      fetchDepartments();
    } else {
      toast.error(result.error || "Failed to remove teacher");
    }
  }

  async function handleAddSubject() {
    if (!selectedSubjectId || !selectedDepartmentId) return;

    const result = await assignSubjectToDepartment(selectedSubjectId, selectedDepartmentId);
    if (result.success) {
      toast.success("Subject added to department");
      setSelectedSubjectId("");
      handleManage(selectedDepartmentId); // Refresh
      fetchDepartments();
    } else {
      toast.error(result.error || "Failed to add subject");
    }
  }

  async function handleRemoveSubject(subjectId: string) {
    const result = await removeSubjectFromDepartment(subjectId);
    if (result.success) {
      toast.success("Subject removed from department");
      if (selectedDepartmentId) handleManage(selectedDepartmentId); // Refresh
      fetchDepartments();
    } else {
      toast.error(result.error || "Failed to remove subject");
    }
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Link href="/admin/academic">
            <Button variant="ghost" size="sm">
              <ChevronLeft className="h-4 w-4 mr-1" />
              Back
            </Button>
          </Link>
          <h1 className="text-2xl font-bold tracking-tight">Academic Departments</h1>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={handleAutoGenerate}
            disabled={autoGenerating}
          >
            {autoGenerating ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Sparkles className="mr-2 h-4 w-4" />
            )}
            Auto Generate
          </Button>
          <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
            <DialogTrigger asChild>
              <Button onClick={handleAddNew}>
                <PlusCircle className="mr-2 h-4 w-4" /> Add Department
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>{selectedDepartmentId ? "Edit Department" : "Add New Department"}</DialogTitle>
                <DialogDescription>
                  {selectedDepartmentId
                    ? "Update the details of the academic department"
                    : "Create a new academic department for your institution"}
                </DialogDescription>
              </DialogHeader>
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                  <FormField
                    control={form.control}
                    name="name"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Department Name</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g. Mathematics" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="description"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Description (Optional)</FormLabel>
                        <FormControl>
                          <Textarea
                            placeholder="Describe the department's focus and responsibilities"
                            {...field}
                            value={field.value || ""}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <DialogFooter>
                    <Button type="submit">
                      {selectedDepartmentId ? "Update" : "Create"}
                    </Button>
                  </DialogFooter>
                </form>
              </Form>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {error && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {loading ? (
        <div className="flex justify-center items-center py-12">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {departments.map((department) => (
            <Card key={department.id} className="hover:shadow-md transition-shadow">
              <CardHeader className="pb-2">
                <div className="flex justify-between items-start">
                  <div className="flex items-center gap-2">
                    <div className="p-2 bg-primary/10 rounded-md text-primary">
                      <Building2 className="h-5 w-5" />
                    </div>
                    <CardTitle className="text-lg">{department.name}</CardTitle>
                  </div>
                  <div className="flex gap-1">
                    <Button variant="ghost" size="sm" className="h-8 w-8 p-0" onClick={() => handleEdit(department.id)}>
                      <Edit className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="sm" className="h-8 w-8 p-0 text-red-500" onClick={() => handleDelete(department.id)}>
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                <CardDescription>{department.description}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4 pt-2">
                  <div className="flex items-center gap-2">
                    <div className="p-1.5 bg-green-50 rounded-md text-green-700">
                      <BookOpen className="h-4 w-4" />
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">Subjects</p>
                      <p className="text-sm font-medium">{department._count?.subjects || 0}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="p-1.5 bg-purple-50 rounded-md text-purple-700">
                      <GraduationCap className="h-4 w-4" />
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">Teachers</p>
                      <p className="text-sm font-medium">{department._count?.teachers || 0}</p>
                    </div>
                  </div>
                </div>
              </CardContent>
              <CardFooter className="pt-0">
                <Button variant="outline" size="sm" className="w-full" onClick={() => handleManage(department.id)}>
                  <UserPlus className="h-4 w-4 mr-2" />
                  Manage Teachers & Subjects
                </Button>
              </CardFooter>
            </Card>
          ))}
        </div>
      )}

      {departments.length === 0 && !loading && (
        <div className="text-center py-12 text-muted-foreground">
          <Building2 className="h-12 w-12 mx-auto text-gray-300 mb-3" />
          <h3 className="text-lg font-medium mb-1">No departments found</h3>
          <p className="text-sm mb-4">Create your first department to get started</p>
          <Button onClick={handleAddNew}>
            <PlusCircle className="mr-2 h-4 w-4" /> Add Department
          </Button>
        </div>
      )}

      {/* Delete Confirmation Dialog */}
      <Dialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete Department</DialogTitle>
            <DialogDescription>
              Are you sure you want to delete this department? This action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteDialogOpen(false)}>
              Cancel
            </Button>
            <Button variant="destructive" onClick={confirmDelete}>
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Manage Teachers & Subjects Dialog */}
      <Dialog open={manageDialogOpen} onOpenChange={setManageDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[80vh]">
          <DialogHeader>
            <DialogTitle>Manage Department: {selectedDepartment?.name}</DialogTitle>
            <DialogDescription>
              Add or remove teachers and subjects from this department.
            </DialogDescription>
          </DialogHeader>

          {loadingAvailable ? (
            <div className="flex justify-center py-8">
              <Loader2 className="h-6 w-6 animate-spin" />
            </div>
          ) : (
            <div className="grid grid-cols-2 gap-4">
              {/* Teachers Section */}
              <div className="space-y-3">
                <h3 className="font-semibold flex items-center gap-2">
                  <GraduationCap className="h-4 w-4" /> Teachers
                </h3>

                {/* Add Teacher */}
                <div className="flex gap-2">
                  <Select value={selectedTeacherId} onValueChange={setSelectedTeacherId}>
                    <SelectTrigger className="flex-1">
                      <SelectValue placeholder="Select teacher" />
                    </SelectTrigger>
                    <SelectContent>
                      {availableTeachers.length === 0 ? (
                        <div className="py-2 px-3 text-sm text-muted-foreground">
                          No teachers available
                        </div>
                      ) : (
                        availableTeachers.map((t) => (
                          <SelectItem key={t.id} value={t.id}>
                            {t.name}
                          </SelectItem>
                        ))
                      )}
                    </SelectContent>
                  </Select>
                  <Button size="sm" onClick={handleAddTeacher} disabled={!selectedTeacherId}>
                    Add
                  </Button>
                </div>

                {/* Current Teachers */}
                <ScrollArea className="h-[200px] border rounded-md p-2">
                  {selectedDepartment?.teachers.length === 0 ? (
                    <div className="text-center py-4 text-muted-foreground text-sm">
                      No teachers assigned
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {selectedDepartment?.teachers.map((teacher) => (
                        <div key={teacher.id} className="flex items-center justify-between p-2 rounded-md bg-muted/50">
                          <div className="flex items-center gap-2">
                            <div className="h-8 w-8 rounded-full bg-primary/10 flex items-center justify-center text-xs font-medium">
                              {teacher.user.firstName[0]}{teacher.user.lastName[0]}
                            </div>
                            <div>
                              <p className="text-sm font-medium">
                                {teacher.user.firstName} {teacher.user.lastName}
                              </p>
                              <p className="text-xs text-muted-foreground">{teacher.employeeId}</p>
                            </div>
                          </div>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 w-7 p-0 text-muted-foreground hover:text-destructive"
                            onClick={() => handleRemoveTeacher(teacher.id)}
                          >
                            <X className="h-4 w-4" />
                          </Button>
                        </div>
                      ))}
                    </div>
                  )}
                </ScrollArea>
              </div>

              {/* Subjects Section */}
              <div className="space-y-3">
                <h3 className="font-semibold flex items-center gap-2">
                  <BookOpen className="h-4 w-4" /> Subjects
                </h3>

                {/* Add Subject */}
                <div className="flex gap-2">
                  <Select value={selectedSubjectId} onValueChange={setSelectedSubjectId}>
                    <SelectTrigger className="flex-1">
                      <SelectValue placeholder="Select subject" />
                    </SelectTrigger>
                    <SelectContent>
                      {availableSubjects.length === 0 ? (
                        <div className="py-2 px-3 text-sm text-muted-foreground">
                          No subjects available
                        </div>
                      ) : (
                        availableSubjects.map((s) => (
                          <SelectItem key={s.id} value={s.id}>
                            {s.name} ({s.code})
                          </SelectItem>
                        ))
                      )}
                    </SelectContent>
                  </Select>
                  <Button size="sm" onClick={handleAddSubject} disabled={!selectedSubjectId}>
                    Add
                  </Button>
                </div>

                {/* Current Subjects */}
                <ScrollArea className="h-[200px] border rounded-md p-2">
                  {selectedDepartment?.subjects.length === 0 ? (
                    <div className="text-center py-4 text-muted-foreground text-sm">
                      No subjects assigned
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {selectedDepartment?.subjects.map((subject) => (
                        <div key={subject.id} className="flex items-center justify-between p-2 rounded-md bg-muted/50">
                          <div>
                            <p className="text-sm font-medium">{subject.name}</p>
                            <p className="text-xs text-muted-foreground">{subject.code}</p>
                          </div>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 w-7 p-0 text-muted-foreground hover:text-destructive"
                            onClick={() => handleRemoveSubject(subject.id)}
                          >
                            <X className="h-4 w-4" />
                          </Button>
                        </div>
                      ))}
                    </div>
                  )}
                </ScrollArea>
              </div>
            </div>
          )}

          <DialogFooter>
            <Button variant="outline" onClick={() => setManageDialogOpen(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Auto-Generate Checklist Dialog */}
      <Dialog open={autoGenerateDialogOpen} onOpenChange={setAutoGenerateDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Auto-Generate Departments</DialogTitle>
            <DialogDescription>
              Select which departments you want to create. Only new departments will be added.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <span className="text-sm text-muted-foreground">
                {selectedTemplates.length} of {availableTemplates.length} selected
              </span>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" onClick={selectAllTemplates}>
                  Select All
                </Button>
                <Button variant="outline" size="sm" onClick={clearAllTemplates}>
                  Clear
                </Button>
              </div>
            </div>

            <ScrollArea className="h-[300px] border rounded-md p-3">
              {availableTemplates.length === 0 ? (
                <p className="text-center text-muted-foreground py-4">
                  All standard departments already exist
                </p>
              ) : (
                <div className="space-y-3">
                  {availableTemplates.map((dept) => (
                    <div
                      key={dept.name}
                      className="flex items-start gap-3 p-2 rounded-md hover:bg-muted/50 cursor-pointer"
                      onClick={() => toggleTemplate(dept.name)}
                    >
                      <Checkbox
                        checked={selectedTemplates.includes(dept.name)}
                        onCheckedChange={() => toggleTemplate(dept.name)}
                      />
                      <div className="flex-1">
                        <p className="font-medium text-sm">{dept.name}</p>
                        <p className="text-xs text-muted-foreground">{dept.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </ScrollArea>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setAutoGenerateDialogOpen(false)}>
              Cancel
            </Button>
            <Button
              onClick={confirmAutoGenerate}
              disabled={autoGenerating || selectedTemplates.length === 0}
            >
              {autoGenerating ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <Sparkles className="mr-2 h-4 w-4" />
              )}
              Generate {selectedTemplates.length} Department{selectedTemplates.length !== 1 ? 's' : ''}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

