import { test, expect } from '@playwright/test';

// Increase test timeout for login flows that involve full page reloads
test.setTimeout(60000);

// Use the credentials generated by tests/generators/setup-core.ts & setup-users.ts
const TEST_SCHOOL_CODE = 'TEST-INTL';
const SUPER_ADMIN = { email: 'superadmin@test.com', pass: 'superadmin123' };
const SCHOOL_ADMIN = { email: 'admin@test-intl.edu', pass: 'admin123' };
const TEACHER = { email: 'teacher@test-intl.edu', pass: 'password123' };
const STUDENT = { email: 'student@test.com', pass: 'password123' };
const PARENT = { email: 'parent@test.com', pass: 'password123' };

test.describe('Authentication & Authorization Flows', () => {

    test('Unauthenticated user is redirected to login from protected route', async ({ page }) => {
        await page.goto('/dashboard');
        // Expect the URL to contain login
        await expect(page).toHaveURL(/.*login/);
    });

    test('Super Admin can login successfully', async ({ page }) => {
        await page.goto('/sd'); // Super admin login route

        // Fill in email
        await page.waitForSelector('input[name="email"]', { state: 'visible' });
        await page.locator('input[name="email"]').click();
        await page.locator('input[name="email"]').fill(SUPER_ADMIN.email);

        // Fill in password
        await page.locator('input[name="password"]').click();
        await page.locator('input[name="password"]').fill(SUPER_ADMIN.pass);
        await page.waitForTimeout(500);

        await page.click('button[type="submit"]');

        // The form uses router.push('/super-admin') after successful signIn
        await expect(page).toHaveURL(/.*super-admin.*/, { timeout: 30000 });
    });

    test('School Admin can login successfully via 3-step Unified Login', async ({ page }) => {
        await page.goto('/login');

        // Step 1: School Code
        await page.waitForSelector('input[name="schoolCode"]', { state: 'visible' });
        await page.locator('input[name="schoolCode"]').click();
        await page.locator('input[name="schoolCode"]').fill(TEST_SCHOOL_CODE);
        await page.waitForTimeout(500);
        await page.click('button[type="submit"]');

        // Step 2: Identifier Form
        await expect(page.locator('input[name="identifier"]')).toBeVisible({ timeout: 10000 });
        await page.locator('input[name="identifier"]').click();
        await page.locator('input[name="identifier"]').fill(SCHOOL_ADMIN.email);
        await page.waitForTimeout(500);
        await page.click('button[type="submit"]');

        // Step 3: Password Form
        await expect(page.locator('input[name="password"]')).toBeVisible({ timeout: 10000 });
        await page.locator('input[name="password"]').click();
        await page.locator('input[name="password"]').fill(SCHOOL_ADMIN.pass);
        await page.waitForTimeout(500);
        await page.click('button[type="submit"]');

        // Should redirect to admin dashboard (via /dashboard → middleware → /admin)
        await expect(page).toHaveURL(/.*admin.*/, { timeout: 30000 });
    });

    test('Teacher can login successfully via 3-step Unified Login', async ({ page }) => {
        await page.goto('/login');

        // Step 1: School Code
        await page.waitForSelector('input[name="schoolCode"]', { state: 'visible' });
        await page.locator('input[name="schoolCode"]').click();
        await page.locator('input[name="schoolCode"]').fill(TEST_SCHOOL_CODE);
        await page.waitForTimeout(500);
        await page.click('button[type="submit"]');

        // Step 2: Identifier Form
        await expect(page.locator('input[name="identifier"]')).toBeVisible({ timeout: 10000 });
        await page.locator('input[name="identifier"]').click();
        await page.locator('input[name="identifier"]').fill(TEACHER.email);
        await page.waitForTimeout(500);
        await page.click('button[type="submit"]');

        // Step 3: Password Form
        await expect(page.locator('input[name="password"]')).toBeVisible({ timeout: 10000 });
        await page.locator('input[name="password"]').click();
        await page.locator('input[name="password"]').fill(TEACHER.pass);
        await page.waitForTimeout(500);
        await page.click('button[type="submit"]');

        // Should redirect to teacher dashboard (via /dashboard → middleware → /teacher)
        await expect(page).toHaveURL(/.*teacher.*/, { timeout: 30000 });
    });

});
