import { test, expect } from '@playwright/test';

test.setTimeout(60000);

// Use the credentials generated by the fixtures
const TEST_SCHOOL_CODE = 'TEST-INTL';

const authenticate = async (page: any, email: string, pass: string) => {
    await page.goto('/login');

    // Login 3-step unified flow
    await page.waitForSelector('input[name="schoolCode"]', { state: 'visible' });
    await page.locator('input[name="schoolCode"]').click();
    await page.locator('input[name="schoolCode"]').fill(TEST_SCHOOL_CODE);
    await page.waitForTimeout(500);
    await page.click('button[type="submit"]');

    await expect(page.locator('input[name="identifier"]')).toBeVisible({ timeout: 10000 });
    await page.locator('input[name="identifier"]').click();
    await page.locator('input[name="identifier"]').fill(email);
    await page.waitForTimeout(500);
    await page.click('button[type="submit"]');

    await expect(page.locator('input[name="password"]')).toBeVisible({ timeout: 10000 });
    await page.locator('input[name="password"]').click();
    await page.locator('input[name="password"]').fill(pass);
    await page.waitForTimeout(500);
    await page.click('button[type="submit"]');

    await expect(page).toHaveURL(/.*(admin|teacher|student).*/, { timeout: 30000 });
};

test.describe('Role Based Protected Routes', () => {

    test('Unauthenticated user is redirected to login from protected route', async ({ page }) => {
        await page.goto('/admin/users/students');
        await expect(page).toHaveURL(/.*login.*/, { timeout: 15000 });
    });

    test('Teacher CANNOT access admin modules', async ({ page }) => {
        await authenticate(page, 'teacher@test-intl.edu', 'password123');

        // Teacher should be at /teacher after login
        await expect(page).toHaveURL(/.*\/teacher.*/, { timeout: 15000 });

        // Try accessing admin route - should be redirected away
        await page.goto('/admin/users/students');

        // Layout-level RBAC redirects to /dashboard, which redirects to /teacher
        // So teacher should NOT remain on /admin/users/students
        await expect(page).not.toHaveURL(/.*\/admin\/users\/students/, { timeout: 15000 });
    });

    test('Student CANNOT access teacher modules', async ({ page }) => {
        await authenticate(page, 'student@test.com', 'password123');

        // Student should be at /student after login
        await expect(page).toHaveURL(/.*\/student.*/, { timeout: 15000 });

        // Try accessing teacher route - should be redirected away
        await page.goto('/teacher/attendance');

        // Layout-level RBAC redirects to /dashboard, which redirects to /student
        await expect(page).not.toHaveURL(/.*\/teacher\/attendance/, { timeout: 15000 });
    });

    test('School Admin CANNOT access super admin modules', async ({ page }) => {
        // School admin uses the unified login (not /sd)
        await authenticate(page, 'admin@test-intl.edu', 'admin123');

        // Admin should be at /admin after login
        await expect(page).toHaveURL(/.*\/admin.*/, { timeout: 15000 });

        // Try accessing super-admin route - should be redirected away
        await page.goto('/super-admin/schools');

        // Both middleware and layout-level RBAC block non-super-admin access
        await expect(page).not.toHaveURL(/.*\/super-admin\/schools/, { timeout: 15000 });
    });

});
