import { test, expect } from '@playwright/test';

test.setTimeout(60000);

// Use the credentials generated by the fixtures
const TEST_SCHOOL_CODE = 'TEST-INTL';

const authenticateAdmin = async (page: any) => {
    await page.goto('/login');

    await page.waitForSelector('input[name="schoolCode"]', { state: 'visible' });
    await page.locator('input[name="schoolCode"]').click();
    await page.locator('input[name="schoolCode"]').fill(TEST_SCHOOL_CODE);
    await page.waitForTimeout(500);
    await page.click('button[type="submit"]');

    await expect(page.locator('input[name="identifier"]')).toBeVisible({ timeout: 10000 });
    await page.locator('input[name="identifier"]').click();
    await page.locator('input[name="identifier"]').fill('admin@test-intl.edu');
    await page.waitForTimeout(500);
    await page.click('button[type="submit"]');

    await expect(page.locator('input[name="password"]')).toBeVisible({ timeout: 10000 });
    await page.locator('input[name="password"]').click();
    await page.locator('input[name="password"]').fill('admin123');
    await page.waitForTimeout(500);
    await page.click('button[type="submit"]');

    await expect(page).toHaveURL(/.*admin.*/, { timeout: 30000 });
};

test.describe('School Admin: User Management', () => {

    test.beforeEach(async ({ page }) => {
        // Authenticate as School Admin before each test
        await authenticateAdmin(page);
    });

    test('should view the list of teachers', async ({ page }) => {
        await page.goto('/admin/users/teachers');

        // Test Teacher generated by fixture should be in the list
        // Use .first() because responsive table renders both desktop and mobile views
        await expect(page.locator('text=Test Teacher').first()).toBeVisible();
        await expect(page.locator('text=teacher@test-intl.edu').first()).toBeVisible();
    });

    test('should view the list of students', async ({ page }) => {
        await page.goto('/admin/users/students');

        // Test Student generated by fixture should be in the list
        // Note: Students table shows Name, Admission ID, Class, Gender - no email column
        await expect(page.locator('text=Test Student').first()).toBeVisible();
    });

    test('should view the list of parents', async ({ page }) => {
        await page.goto('/admin/users/parents');

        // Test Parent generated by fixture
        await expect(page.locator('text=Test Parent').first()).toBeVisible();
        await expect(page.locator('text=parent@test.com').first()).toBeVisible();
    });

    // Test that the "Add Student" link navigates to the create page
    test('should have an Add Student button that links to create page', async ({ page }) => {
        await page.goto('/admin/users/students');

        // The Add Student button is actually a link to /admin/users/students/create
        const addStudentLink = page.getByRole('link', { name: /Add Student/i });
        await expect(addStudentLink).toBeVisible({ timeout: 15000 });

        // Verify it links to the correct URL
        await expect(addStudentLink).toHaveAttribute('href', /.*students\/create/);
    });
});
