-- CreateTable
CREATE TABLE "school_branding" (
    "id" TEXT NOT NULL,
    "schoolName" TEXT NOT NULL,
    "tagline" TEXT,
    "logo" TEXT,
    "favicon" TEXT,
    "primaryColor" TEXT NOT NULL DEFAULT '#3b82f6',
    "secondaryColor" TEXT NOT NULL DEFAULT '#8b5cf6',
    "accentColor" TEXT,
    "emailLogo" TEXT,
    "emailFooter" TEXT,
    "emailSignature" TEXT,
    "letterheadLogo" TEXT,
    "letterheadText" TEXT,
    "documentFooter" TEXT,
    "address" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "website" TEXT,
    "facebookUrl" TEXT,
    "twitterUrl" TEXT,
    "linkedinUrl" TEXT,
    "instagramUrl" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "school_branding_pkey" PRIMARY KEY ("id")
);
